-- Table: public.anotacoes

-- DROP TABLE IF EXISTS public.anotacoes;

CREATE TABLE IF NOT EXISTS public.anotacoes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    aula character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tipo smallint NOT NULL,
    revisado boolean NOT NULL,
    CONSTRAINT anotacoes_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.anotacoes
    OWNER to postgres;
