DROP TABLE IF EXISTS concorrentes;

CREATE TABLE IF NOT EXISTS concorrentes (

   id integer primary key generated by default as identity,

   pais character varying(100) NOT NULL,

   nomerepresentante character varying(100) NOT NULL,

   nomemusica character varying(100) NOT NULL,

   ronda smallint NOT NULL,

   pontosjuri smallint NOT NULL,

   pontostelevoto smallint NOT NULL,

   totalpontos smallint NOT NULL );
